### ISSUE TITLE
Fix typo in readme

### ISSUE THREAD

**Issue by arshadkazmi42** [arshadkazmi42/flip-remote#1]
There is a type in `Usage` in readme here
https://github.com/arshadkazmi42/flip-remote#usage

`belo command` should be changed to `below command`

**Comment by emmanio** [comment]
Hello! I'm keen to fix your issue, just trying to get familiar with contributing to projects on github. Thank you :)

**Comment by arshadkazmi42** [comment]
@emmanio Go ahead. Create a PR.
