### ISSUE TITLE
Pull request template

### ISSUE THREAD

**Issue by arshadkazmi42** [arshadkazmi42/flip-remote#13]
Add `PULL_REQUEST_TEMPLATE.md` file in root directory with below content in it
```
Fixes #issuenumber
-
```

**Comment by neilr1** [comment]
Hi, may I claim this issue?

**Comment by arshadkazmi42** [comment]
@neilr1 Yes. Go ahead create a PR

**Comment by neilr1** [comment]
Got it thanks! I've created a PR.
#14
