### ISSUE TITLE
fix vulnerability

### ISSUE THREAD

**Issue by arshadkazmi42** [arshadkazmi42/flip-remote#32]
- Delete package-lock.json
- Run `npm install`
- Commit the updated package-lock.json
- Create pull request

**Comment by imanishbarnwal** [comment]
Hello, @arshadkazmi42 I will be glad to take this issue. Can I do this?

**Comment by arshadkazmi42** [comment]
@imanishbarnwal cool. Go ahead

**Comment by imanishbarnwal** [comment]
> @imanishbarnwal cool. Go ahead

Okay sure. Thanks, @arshadkazmi42

**Comment by imanishbarnwal** [comment]
Hello, @arshadkazmi42 I had updated the package-lock.json can you please check them?
