### ISSUE TITLE
Add badges to readme

### ISSUE THREAD

**Issue by arshadkazmi42** [arshadkazmi42/flip-remote#40]
1. Install npm badger `npm install npm-badger -g`
2. Clone this repository `git clone https://github.com/arshadkazmi42/flip-remote`
3. Go to root directory `cd flip-remote`
4. Run npm badger `npm-badger`
5. Commit `README.md` file
6. Create Pull Request

**Comment by pwnb0y** [comment]
assign it to me

**Comment by arshadkazmi42** [comment]
Assigned

**Comment by Ayushbajpai19** [comment]
I would like to take this issue for hacktoberfest
